/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class TestClasspath {
    @Test void extraFileIsFound() {
        assertTrue(TestClasspath.class.getResource("/extraFile") != null);
    }
}
